name: gitConfig
description: "Sets git username/email and push behavior"

inputs:
  email:
    description: 'Email to set for config'
    required: true
  token:
    description: 'Token'
    required: true

runs:
  using: composite
  steps:
    - run: git config --global push.default current
      shell: bash
    - run: git config --global user.email ${{ inputs.email }}
      shell: bash
    - run: git config user.name 'Release Bot'
      shell: bash
    - run: git config --global remote.origin.url 'https://${{ inputs.token }}@github.com/${{ inputs.email }}/salesforcedx-vscode-fork.git'
      shell: bash